
name: Snapshot Build
on:
  pull_request:
    branches:    
      - 'main'
      - 'dev'
jobs:
  # build_ios:
  #   runs-on: macos-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-java@v1
  #     with:
  #       java-version: '11'
  #   - uses: subosito/flutter-action@v1
  #     with:
  #       flutter-version: '2.10.2'
  #       channel: 'stable'

  build_android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.10.2'
        channel: 'stable'
        cache: true
        cache-key: flutter
        cache-path: ${{ runner.tool_cache }}/flutter
    
    - name: Install Depencies
      run: flutter pub get

    - name: create config
      run: |
        echo VITE_SUPABASE_ANNON_KEY=$VITE_SUPABASE_ANNON_KEY >> .env
        echo VITE_SUPABASE_URL=$VITE_SUPABASE_URL >> .env
        echo VITE_API_URL=$VITE_API_URL >> .env
        echo VITE_ANON_DOMAIN=$VITE_ANON_DOMAIN >> .env
      env:
        VITE_SUPABASE_ANNON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24ifQ.625_WdcF3KHqz5amU0x2X5WWHP-OEs_4qj0ssLNHzTs
        VITE_SUPABASE_URL: "http://localhost:54321"
        VITE_API_URL: "http://localhost:5000/api/v1"
        VITE_ANON_DOMAIN: "@anon-users.pidsamhai.com"

    - name: Build Apk
      run: flutter build apk --profile

    - uses: actions/upload-artifact@v2
      with:
        name: android-profile
        path: build/app/outputs/flutter-apk/app-profile.apk
        retention-days: 7