
name: Snapshot Build
on:
  pull_request:
    branches:    
      - 'main'
      - 'dev'
    types: [synchronize, opened, reopened, edited]
    
jobs:
  # build_ios:
  #   runs-on: macos-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-java@v1
  #     with:
  #       java-version: '11'
  #   - uses: subosito/flutter-action@v1
  #     with:
  #       flutter-version: '2.10.2'
  #       channel: 'stable'

  build_android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.10.2'
        channel: 'stable'
        cache: true
        cache-key: flutter
        cache-path: ${{ runner.tool_cache }}/flutter
    
    - name: Install Depencies
      run: flutter pub get

    - name: create config
      run: |
        echo SUPABASE_API_URL=$SUPABASE_API_URL >> .env
        echo SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY >> .env
        echo API_URL=$API_URL >> .env
      env:
        SUPABASE_API_URL: "http://localhost:54321"
        SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24ifQ.625_WdcF3KHqz5amU0x2X5WWHP-OEs_4qj0ssLNHzTs"
        API_URL: "http://localhost:5000/api/v1"

    - name: Build Apk
      run: flutter build apk --profile --split-per-abi

    - uses: actions/upload-artifact@v2
      with:
        name: android-profile-armv8
        path: build/app/outputs/flutter-apk/app-arm64-v8a-profile.apk
        retention-days: 3

    - uses: actions/upload-artifact@v2
      with:
        name: android-release-x86-64
        path: build/app/outputs/flutter-apk/app-x86_64-profile.apk
        retention-days: 3